# Generated by Django 3.1.5 on 2021-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_client_curr_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trancation',
            name='sector',
            field=models.CharField(max_length=100),
        ),
    ]
