# Generated by Django 3.1.5 on 2021-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20210131_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='curr_bal',
            field=models.IntegerField(default=0),
        ),
    ]
