# Generated by Django 3.1.5 on 2021-01-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20210131_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='curr_bal',
        ),
    ]
