# Generated by Django 3.1.5 on 2021-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20210201_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='trancation',
            name='verifed',
            field=models.BooleanField(default=False),
        ),
    ]
