# Generated by Django 3.1.5 on 2021-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_trancation_verifed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trancation',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trancation',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
