# Generated by Django 3.1.5 on 2021-02-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20210202_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trancation',
            options={'ordering': ['booking_date']},
        ),
        migrations.AlterField(
            model_name='trancation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
