# Generated by Django 3.1.5 on 2021-02-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20210202_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trancation',
            name='hidden',
        ),
    ]
