# Generated by Django 3.1.6 on 2021-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_remove_trancation_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trancation',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
