# Generated by Django 3.1.6 on 2021-02-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_auto_20210219_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobno',
        ),
    ]
