# Generated by Django 3.2.8 on 2021-12-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_trancation_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
